### ISSUE TITLE
이거 어떻게 하면 제대로 번역 되나요??

### ISSUE THREAD

**Issue by LeePC** [HelloKS/ezTransWeb#3]
엔드포인트 설정했지만
"ezTranslator J2K Web Wrapper" 라고만 뜨고 번역이 안됩니다
어떻게 하는지 알려주실순 없나요??

**Comment by HelloKS** [comment]
안녕하세요.
XUnity.AutoTranslator용으로 사용하시는 것으로 보이는데 맞으신가요?

Endpoint를 CustomTranslate로,
Url을 http://127.0.0.1:5000/translate로 설정해보시기 바랍니다.

관련 매뉴얼이 부족한 부분이 있는 것 같아 조만간 설치와 설정 관련 문서를 만들어 보겠습니다.

그리고 같은 이슈를 계속 생성하셨다가 닫으시는데 가급적 수정 기능을 사용해 주십시오.
감사합니다.

**Comment by HelloKS** [comment]
3265cd06 커밋에서 설정 관련 문서를 추가하였습니다.
이슈를 닫습니다.
