### ISSUE TITLE
저기 외부주소로는 연결이 안되나요??

### ISSUE THREAD

**Issue by LeePC** [HelloKS/ezTransWeb#4]
외부주소로 연결하려고 하니깐 연결이 안되고 차단되버리던데
외부주소로 할수있게 만들어주시면 안될까요??
제가 호스팅이 있는데 외부주소로 연결시켜 해보고싶습니다
포트는 5000포트 및 21포트 443 포트 80포트 8080 포트가 열려있습니다

**Comment by HelloKS** [comment]
안녕하세요.

외부 접속 관련해서는 `eztrans.py`에서 `127.0.0.1`을 삭제해 보시기 바랍니다.
https://github.com/HelloKS/ezTransWeb/blob/8b919fd566a76501278a1ae87677cc5c638919a0/eztrans.py#L41

제작할때도 로컬에서 사용하기 위해 만들었고, 앞으로도 호스팅용으로는 개발하거나 혹은 지원할 계획이 없습니다.
감사합니다.
