### ISSUE TITLE
일단 xunity를 최신버젼으로 번역하려고 하면 문제가 생겨버리네요

### ISSUE THREAD

**Issue by LeePC** [HelloKS/ezTransWeb#6]
xunity는 구버젼은 현재 번역이 잘됩니다
하지만 최신버젼으로 하려고 하면 번역이 안되는 현상이 나와버리네요
밑에분 말로는 인증서 문제라고 하시는데 이걸 어떻게 해야될지 모르겠네요 ㅠㅠ

**Comment by LeePC** [comment]
일단 해결방법은 찾았습니다
문제가 뭐냐면
파이썬 32비트 버젼이 너무 높아서 그런문제가 생긴듯 합니다

파이썬은 3.7.X 버젼을 사용하시기 바랍니다
그렇다고 3.7.10 이상버젼은 사용하지마세요
보니깐 버젼 문제더라구요....

**Comment by HelloKS** [comment]
내부적으로 사용하는 Gevent 라이브러리가 Python 3.8 이후로는 x64 환경만 지원하여 생기는 문제점으로 판단하여, 해당 라이브러리 사용을 중단하였습니다. (7296b9a)
현재 최신 버전인 Python 3.11.4에서 정상 설치 및 작동 확인하여 이슈를 닫습니다.
